name: CI

on:
  push:

permissions:
  contents: read

jobs:
  build-test:
    name: Test ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-x86_64
            shell: bash
          - os: macos-13
            label: macos-x86_64
            shell: bash
          - os: macos-14
            label: macos-aarch64
            shell: bash
          - os: windows-latest
            label: windows-x86_64
            shell: pwsh

    env:
      BUILD_DIR: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake (Linux/macOS)
        if: runner.os != 'Windows'
        uses: lukka/get-cmake@v3.31.0

      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cmake -S . -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake -S . -B "$env:BUILD_DIR" -G "Visual Studio 17 2022" -A x64

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cmake --build "$BUILD_DIR" --config Release --parallel

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake --build "$env:BUILD_DIR" --config Release

      - name: Test (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ctest --test-dir "$BUILD_DIR" --output-on-failure

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ctest --test-dir "$env:BUILD_DIR" -C Release --output-on-failure

